# Site settings
title: Adaptris
description: 'Integration anytime any place anywhere.'
url: 'http://interlok.adaptris.net'
baseurl: ''
# Everything up to <!-- more --> is included in the excerprt.

excerpt_separator: <!-- more -->
author:
  name: 'Adaptris'
  # email: josh@joshgerdes.com
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  adaptris

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /blog/:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'LICENSE', 'docker-compose.yml']
